//LOCALHOST
### Get all contacts
http://localhost:8080/contacts

### Get a single contact
http://localhost:8080/contacts/650a73a0ebc57596a688a47a

### Post a new Contact
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Norville",
  "lastName": "Rogers",
  "email": "shaggy@mysteryinc.org",
  "favoriteColor": "Green",
  "birthday": "1969-09-13"
}

### Update and Existing Contact
PUT http://localhost:8080/contacts/650a73a0ebc57596a688a47a HTTP/1.1
Content-Type: application/json

{
    "firstName": "Norville",
    "lastName": "Rogers",
    "email": "shaggy@mysteryinc.org",
    "favoriteColor": "Green",
    "birthday": "2020-09-13"
}

### Delete a contact
DELETE http://localhost:8080/contacts/650a73a0ebc57596a688a47a HTTP/1.1


// Production
### Get all Contacts
https://cse-314-week-2-contacts-api-part-2.onrender.com/
### Get a single contact
https://cse-314-week-2-contacts-api-part-2.onrender.com/contacts/650a73a0ebc57596a688a47a

### Post a new Contact
POST https://cse-314-week-2-contacts-api-part-2.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Norville",
  "lastName": "Rogers",
  "email": "shaggy@mysteryinc.org",
  "favoriteColor": "Green",
  "birthday": "1969-09-13"
}

### Update and Existing Contact
PUT https://cse-314-week-2-contacts-api-part-2.onrender.com/contacts/650a73a0ebc57596a688a47a HTTP/1.1
Content-Type: application/json

{
    "firstName": "Norville",
    "lastName": "Rogers",
    "email": "shaggy@mysteryinc.org",
    "favoriteColor": "Green",
    "birthday": "2020-09-13"
}

### Delete a contact
DELETE https://cse-314-week-2-contacts-api-part-2.onrender.com/contacts/650a73a0ebc57596a688a47a HTTP/1.1