//LOCALHOST
### Get all contacts
http://localhost:3000/contacts

### Get a single contact
http://localhost:3000/contacts/6508a8efe4a9139f63835544

### Post a new Contact
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Norville",
  "lastName": "Rogers",
  "email": "shaggy@mysteryinc.org",
  "favoriteColor": "Green",
  "birthday": "1969-09-13"
}

### Update and Existing Contact
PUT http://localhost:3000/contacts/6508bd0a5d795eb8bdb0da48 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Norville",
    "lastName": "Rogers",
    "email": "shaggy@mysteryinc.org",
    "favoriteColor": "Green",
    "birthday": "2020-09-13"
}

### Delete a contact
DELETE http://localhost:3000/contacts/6508bd0a5d795eb8bdb0da48 HTTP/1.1


// Production
### Get all Contacts
https://project-1-contacts.onrender.com/contacts

### Get a single contact
https://project-1-contacts.onrender.com/contacts/6504f1a8fa72d2051339b44d
